https://stackoverflow.com/questions/60003673/restrict-the-sum-of-outputs-in-a-neural-network-regression-keras/

BTW, using random traning and validation data ensures adherence to the SISO principle.

In [1]:
from tensorflow.kerasras.layers import *

In [7]:
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

In [9]:
import numpy as np

In [3]:
input_size = 10
output_size = 5

In [10]:
X = np.random.random((100, input_size))
Y = np.random.random((100, output_size))
X_t, Y_t = np.random.random((20, input_size)), np.random.random((20, output_size))

In [23]:
from tensorflow.keras import backend as K

In [24]:
input_x = Input(shape=(input_size,))
output = Dense(512, activation=PReLU())(input_x)
output = Dropout(0.5)(output)
output = Dense(512, activation=PReLU())(output)
output = Dropout(0.5)(output)
output = Dense(16, activation=PReLU())(output)
output = Dropout(0.3)(output)
outputs = Dense(output_size, activation='relu')(output)
outputs = Lambda(lambda x: x / K.sum(x))(outputs)

nn = Model(inputs=input_x, outputs=outputs)
es = EarlyStopping(monitor='val_loss',min_delta=0,patience=10,verbose=1, mode='auto')
opt=Adam(lr=0.001, decay=1-0.995)
nn.compile(loss='mean_absolute_error', optimizer=opt)
history = nn.fit(X, Y, validation_data = (X_t, Y_t), epochs=100, verbose=1, callbacks=[es])
history

Train on 100 samples, validate on 20 samples
Epoch 1/100
100/100 [==============================] - 2s 16ms/sample - loss: 0.5010 - val_loss: 0.5267
Epoch 2/100
100/100 [==============================] - 0s 543us/sample - loss: 0.5011 - val_loss: 0.5267
Epoch 3/100
100/100 [==============================] - 0s 508us/sample - loss: 0.5010 - val_loss: 0.5267
Epoch 4/100
100/100 [==============================] - 0s 543us/sample - loss: 0.5012 - val_loss: 0.5267
Epoch 5/100
100/100 [==============================] - 0s 514us/sample - loss: 0.5009 - val_loss: 0.5268
Epoch 6/100
100/100 [==============================] - 0s 525us/sample - loss: 0.5008 - val_loss: 0.5268
Epoch 7/100
100/100 [==============================] - 0s 547us/sample - loss: 0.5014 - val_loss: 0.5268
Epoch 8/100
100/100 [==============================] - 0s 481us/sample - loss: 0.5013 - val_loss: 0.5269
Epoch 9/100
100/100 [==============================] - 0s 550us/sample - loss: 0.5014 - val_loss: 0.5269
Epoch 10/10

In [25]:
d = nn.predict(np.random.random((1, input_size)))

In [26]:
d

array([[0.17374235, 0.4271169 , 0.39914078, 0.        , 0.        ]],
      dtype=float32)

In [27]:
d.sum()

1.0

In [19]:
from scipy.special import softmax

In [20]:
softmax([1, 2, 3, 4])

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [21]:
10 * softmax([1, 2, 3, 4])

array([0.32058603, 0.87144319, 2.36882818, 6.4391426 ])