We could think of many ways for numbering the natural numbers, or even $Z$, integers.
But let's see how a neat closed-form function taken from Marecki, "Grafy i rekurencje" p. 64:

$\propto_2(x, x) = \frac{(x+y)(x+y+1)}{2} + x$

BTW, the symbol $\propto$ means "proportionality"... ($\LaTeX$ - `\propto`)

In [3]:
import numpy as np
x, y = np.mgrid[:10, :10]

(x+y)*(x+y+1) // 2 + x

array([[  0,   1,   3,   6,  10,  15,  21,  28,  36,  45],
       [  2,   4,   7,  11,  16,  22,  29,  37,  46,  56],
       [  5,   8,  12,  17,  23,  30,  38,  47,  57,  68],
       [  9,  13,  18,  24,  31,  39,  48,  58,  69,  81],
       [ 14,  19,  25,  32,  40,  49,  59,  70,  82,  95],
       [ 20,  26,  33,  41,  50,  60,  71,  83,  96, 110],
       [ 27,  34,  42,  51,  61,  72,  84,  97, 111, 126],
       [ 35,  43,  52,  62,  73,  85,  98, 112, 127, 143],
       [ 44,  53,  63,  74,  86,  99, 113, 128, 144, 161],
       [ 54,  64,  75,  87, 100, 114, 129, 145, 162, 180]])

It's so close to symmetry, that it's easy to flip it and go first down, then right-up:

In [5]:
(x+y)*(x+y+1) // 2 + y

array([[  0,   2,   5,   9,  14,  20,  27,  35,  44,  54],
       [  1,   4,   8,  13,  19,  26,  34,  43,  53,  64],
       [  3,   7,  12,  18,  25,  33,  42,  52,  63,  75],
       [  6,  11,  17,  24,  32,  41,  51,  62,  74,  87],
       [ 10,  16,  23,  31,  40,  50,  61,  73,  86, 100],
       [ 15,  22,  30,  39,  49,  60,  72,  85,  99, 114],
       [ 21,  29,  38,  48,  59,  71,  84,  98, 113, 129],
       [ 28,  37,  47,  58,  70,  83,  97, 112, 128, 145],
       [ 36,  46,  57,  69,  82,  96, 111, 127, 144, 162],
       [ 45,  56,  68,  81,  95, 110, 126, 143, 161, 180]])

Why does this even work? Well, the first term is equal to a triangular number $T_{x+y}$.
This happens to be the number of elements above the diagonal $x+y$. The free term then
determines the position within the diagonal, if it's $x$ then we go the direction it increases:

In [7]:
x[:3]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

i.e. down, and to keep $x+y$ constant, y has to decrease:

In [8]:
y[:3]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

Which is to the left...

Wait, shouldn't I have written `y, x = np.mgrid[:10, :10]` at the beginning instead?

### What to do next?

Well, it would be nice to find the inverse function, which works nice (even if not closed form, but with some floors of square roots etc.)

I'd introduce the term _triangular remainder_ $tr_n$, where $n = T_x + tr_n$, and $T_x$ is the largest triangular number $\le n$. And it happens to be the "free term", the value of one of the coordinates.