In [1]:
import numpy as np
from numpy.linalg import matrix_power
EXPONENT = 80

In [2]:
a = np.array([[1, 1], [1, 0]], dtype=np.int)
matrix_power(a, EXPONENT)

array([[-945834654, -285007387],
       [-285007387, -660827267]])

In [3]:
a = np.array([[1, 1], [1, 0]], dtype=object)
matrix_power(a, EXPONENT)

array([[37889062373143906, 23416728348467685],
       [23416728348467685, 14472334024676221]], dtype=object)

In [4]:
a = np.array([[1, 1], [1, 0]], dtype=object)
matrix_power(np.eye(2) @ a, EXPONENT)

array([[3.78890623731439e+16, 2.341672834846769e+16],
       [2.341672834846769e+16, 1.447233402467622e+16]], dtype=object)

In [5]:
a = np.array([[1, 1], [1, 0]], dtype=object)
matrix_power(np.eye(2, dtype=np.int) @ a, EXPONENT)

array([[37889062373143906, 23416728348467685],
       [23416728348467685, 14472334024676221]], dtype=object)

In [6]:
a = np.array([[1, 1], [1, 0]], dtype=np.int)
pow(a, EXPONENT)

array([[1, 1],
       [1, 0]], dtype=int32)