# How to intersperse an array with zeros

By creating `zeros_like` it, stacking and flattening.

In [1]:
import numpy as np

shape = (1, 2, 3)

In [2]:
z = np.zeros(3)

In [3]:
np.stack((z, shape), axis=1)

array([[0., 1.],
       [0., 2.],
       [0., 3.]])

In [4]:
np.hstack((z, shape))

array([0., 0., 0., 1., 2., 3.])

In [5]:
np.vstack((z, shape))

array([[0., 0., 0.],
       [1., 2., 3.]])

In [6]:
np.stack((z, shape), axis=0)

array([[0., 0., 0.],
       [1., 2., 3.]])

In [7]:
np.stack((z, shape))

array([[0., 0., 0.],
       [1., 2., 3.]])

In [8]:
np.stack((z, shape)).flatten('F')

array([0., 1., 0., 2., 0., 3.])

In [9]:
np.stack((z, shape), axis=1).flatten()

array([0., 1., 0., 2., 0., 3.])