# MinMaxScaler

Can it scale, when the feature is uniform?

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
scaler = MinMaxScaler()

In [5]:
scaler.fit_transform([[2, 2, 2]])

array([[0., 0., 0.]])

In [6]:
scaler.fit_transform([[2], [2], [2]])

array([[0.],
       [0.],
       [0.]])

In [10]:
# ValueError- wrong shape
scaler.fit_transform([2, 2, 2])

ValueError: Expected 2D array, got 1D array instead:
array=[2. 2. 2.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [11]:
import numpy as np

In [12]:
np.array([2, 2, 2]).reshape(-1, 1) # "single feature"

array([[2],
       [2],
       [2]])

In [13]:
np.array([2, 2, 2]).reshape(1, -1) # "single sample"

array([[2, 2, 2]])

In [14]:
scaler.fit_transform([[1, 2, 3], [4, 5, 6]])

array([[0., 0., 0.],
       [1., 1., 1.]])

In [16]:
scaler.data_min_

array([1., 2., 3.])